# Generated by Django 5.2.5 on 2025-10-19 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('omarov', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Photo',
        ),
    ]
