# Generated by Django 5.2.5 on 2025-10-18 19:47

import django_resized.forms
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('omarov', '0002_alter_photo_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='image',
            field=django_resized.forms.ResizedImageField(crop=None, force_format='WEBP', keep_meta=True, quality=100, scale=None, size=[450, 600], upload_to='photos/'),
        ),
    ]
