services:
  django-web:
    build: .
    container_name: django-docker
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    env_file: .env
    command: ["python", "manage.py", "runserver", "0.0.0.0:8000"]